source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'MBProgressHUD', '~> 0.9.1'

use_frameworks!

prepare_command = <<-CMD
SUPPORTED_LOCALES="['base', 'en']"
find . -type d ! -name "*$SUPPORTED_LOCALES.lproj" | grep .lproj | xargs rm -rf
CMD